SELECT b.REST_ID, b.REST_NAME, b.FOOD_TYPE, b.FAVORITES, b.ADDRESS, ROUND(AVG(a.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS a
LEFT JOIN REST_INFO AS b
ON b.REST_ID = a.REST_ID
GROUP BY a.REST_ID
HAVING b.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;
